# Generated by Django 4.2.11 on 2024-10-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('linkedin', models.CharField(max_length=200)),
                ('github', models.CharField(max_length=200)),
                ('profissao', models.CharField(max_length=200)),
            ],
        ),
    ]
