"""
Django settings for djangorest_py project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR.parent / 'arch' / 'web'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#vamos buscar no arquivo env o valor de SECRET_KEY e atribuir ao settings do projeto
SECRET_KEY = os.getenv('SECRET_KEY', 'NaoEncontrada')

# SECURITY WARNING: don't run with debug turned on in production!
#vamos buscar no arquivo env o valor de DEBUG e atribuir ao settings do projeto
DEBUG = bool(int(os.getenv('DEBUG', 0)))


#no allowed hosts, vamos usar metodos string para pegarmos o valor da variavel de ambiente,
#tomando cuidado para retirar as virgulas e os espacos (caso haja mais de um hoost)
ALLOWED_HOSTS = [
    hosts.strip() for hosts in os.getenv('ALLOWED_HOSTS','').split(',')
    if hosts.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangorest_py.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangorest_py.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#vamos buscar no arquivo env os valores da database e atribuir ao settings do projeto
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'NaoEncontrada'),
        'NAME': os.getenv('POSTGRES_DB', 'NaoEncontrada'),
        'USER': os.getenv('POSTGRES_USER', 'NaoEncontrada'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'NaoEncontrada'),
        'HOST': os.getenv('POSTGRES_HOST', 'NaoEncontrada'),
        'PORT': os.getenv('POSTGRES_PORT', 'NaoEncontrada'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
# /arch/web/static
STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = '/media/'
# /arch/web/media
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
